---
title: "BHq (1995) Simulation on Correlated Data"
author: "Lei Sun"
date: 2018-05-12
output:
  html_document:
    code_folding: hide
---

## Alternative: 1000 $\pm3$, 9000 zeroes

```{r, cache = TRUE}
set.seed(1995)

n <- 1e4
d <- 5
m <- 1000

B <- matrix(rnorm(n * d), n, d)
normalize.constant <- sqrt(rowSums(B^2) + 1)
Z <- replicate(m, 
  (colSums(t(B) * rnorm(d)) + rnorm(n)) / normalize.constant
)

sd.Z <- apply(Z, 2, sd)
group <- cut(sd.Z, breaks = c(0, 0.95, 1.05, Inf), labels = c("Deflated Noise", "In-between", "Inflated Noise"))

theta <- c(rep(c(-1, 1) * 3, each = 0.05 * n), rep(0, 0.9 * n))
X <- theta + Z

p <- 2 * pnorm(-abs(X))
```

```{r}
q <- 0.1
p.BH <- apply(p, 2, p.adjust, method = "BH")
BH.rej <- apply(p.BH, 2, function(x){x <= q})
```

```{r}
FDP.fun <- function (rej.id, theta) {
  sum(theta[rej.id] == 0) / max(1, length(theta[rej.id]))
}
FDP <- apply(BH.rej, 2, FDP.fun, theta)
```

```{r}
## Boxplot of FDP for each group
boxplot(FDP ~ group, ylab = "FDP")
abline(h = q, lty = 2, col = "red")
points(1 : 3, tapply(FDP, group, mean), col = "blue", pch = 13)
## Mean of FDP for each group
tapply(FDP, group, mean)
## sd of FDP for each group
tapply(FDP, group, sd)
## 95% CI of the mean of FDP for each group
tapply(FDP, group, function(x){t.test(x)$conf.int})
## 95% CI of the mean of FDP overall
t.test(FDP)$conf.int
```
